# Generated by Django 4.2.2 on 2023-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risunki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30, null=True)),
                ('canvas', models.CharField(max_length=20)),
                ('paints', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
