# Generated by Django 4.2.2 on 2023-06-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risunki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='risunki',
            table='risunki',
        ),
    ]
