# Generated by Django 4.2.2 on 2023-06-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risunki', '0002_alter_risunki_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risunki',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
